version: "2"
services:
  main:
    container_name: test_main
    build: ./docker/
    env_file: ./docker/env
    tty: true
    volumes:
      - ./:/var/www/dev/.
    ports:
      - "3306:3306"
      - "80:80"
      - "443:443"
  db:
    image: mysql:5
    container_name: test_db
    env_file: ./docker/env
    command: mysqld --sql_mode=""
    volumes:
      - ./docker/db/data:/var/lib/mysql
    network_mode: "service:main"
    depends_on:
      - main
  nginx:
    build: ./docker/nginx
    container_name: test_nginx
    command: ["sh", "-c", "./docker/nginx/init.sh; nginx -g 'daemon off;'"]
    volumes:
      - ./:/var/www/dev/
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php
      - main
    network_mode: "service:main"
  php:
    build: ./docker/php
    container_name: test_php
    depends_on:
      - db
      - main
    entrypoint: ""
    command: ["sh", "-c", "./docker/php/init.sh; php-fpm"]
    volumes:
      - ./:/var/www/dev/
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    network_mode: "service:main"
